#!/usr/bin/python

from core.impl.rg_run import *

if __name__ == '__main__':
    set_modul_path()
    import interface,core.impl
    import pylon
    core.impl.setup()
    pylon.setup()
    import websys
    websys.setup()
    main()

