#!/usr/bin/python

import os

if __name__ == '__main__':
    import  core.run_env
    core.run_env.set_modul_path()
    import setting
    import interface
    import pylon, core.impl , check
    root  = os.path.dirname(os.path.realpath(__file__))
    setting.rg_root = root
    core.impl.setup()
    pylon.setup()
    check.setup()
    import websys
    websys.setup()
    import core.impl.rg_run
    if core.impl.rg_run.main() :
        exit(0)
    else :
        exit(-1)

